const path = {
    passwordDisabled: require('../res/images/passwordDisabled.png'),
    'back': require('../res/images/back.png'),
    'eyeIcon': require('../res/images/eyeIcon.png'),
    'Forgot Password': require('../res/images/forgotPassword.png'),
    'Reset': require('../res/images/reset.png'),
    "Verification": require('../res/images/verification.png'),
    "checkMark": require('../res/images/checkMark.png'),
    //TABS
    "busBreakdownActive": require('../res/images/busBreakdownActive.png'),
    "busBreakdownInactive": require('../res/images/busBreakdownInactive.png'),
    "busRouteActive": require('../res/images/busRouteActive.png'),
    "busRouteInactive": require('../res/images/busRouteInactive.png'),
    "callForHelpActive": require('../res/images/callForHelpActive.png'),
    "callForHelpInactive": require('../res/images/callForHelpInactive.png'),
    "historyInactive": require('../res/images/HistoryInactive.png'),
    "historyActive": require('../res/images/HistoryActive.png'),
    "moreActive": require('../res/images/moreActive.png'),
    "moreInactive": require('../res/images/moreInactive.png'),
    //Screens
    "userIcon": require('../res/images/userIcon.png'),
    "logout": require('../res/images/logout.png'),
    "inbox": require('../res/images/inbox.png'),
    "setting": require('../res/images/setting.png'),
    "message": require('../res/images/message.png'),

    "Other reason": require('../res/images/otherReason.png'),
    "Engine breakdown": require('../res/images/engineBreakdown.png'),
    "Empty fuel": require('../res/images/emptyFuel.png'),
    "Leaked Tires": require('../res/images/leakedTires.png'),
    "logo": require('../res/images/logo.png'),
    "locationRed": require('../res/images/locationRed.png'),
    "locationBlue": require('../res/images/locationBlue.png'),
    "tiltArrow": require('../res/images/tiltArrow.png'),
    "backBlack": require('../res/images/backBlack.png'),
    "arrow": require('../res/images/arrow.png'),
}
export default path;